### ISSUE TITLE
Signs with the first cert in the list

### ISSUE THREAD

**Issue by waderobson** [JeremyAgost/Hancock#1]
Hello Jeremy,

First of all, what an amazing app!!. 
I seem to be having a problem when I sign the profile with the selected certificate.
![image](https://cloud.githubusercontent.com/assets/1497790/16415778/f80d690a-3d0c-11e6-8bf7-319f6acf9ef5.png)
I'm getting the first cert in the list instead.

**Comment by JeremyAgost** [comment]
I fixed it in 1.0 :)
