### ISSUE TITLE
Attempting to sign a mobileconfig file results in trying to use productsign?

### ISSUE THREAD

**Issue by WardsParadox** [JeremyAgost/Hancock#3]
![screenflow](https://user-images.githubusercontent.com/8117192/28292466-50167550-6b0c-11e7-9b14-c3f67da12522.gif)
If you drag n drop mobileconfig's still work, but if you choose to by clicking on the button, it will try and use product sign.

**Comment by groob** [comment]
The bug is here https://github.com/JeremyAgost/Hancock/blob/dc260701d96589bbd81378963f463679818852d3/Hancock/ViewController.mm#L97

Can be fixed by replacing `signPackageFile` with `signFile` which handles both file types.

**Comment by JeremyAgost** [comment]
Ah, good catch. Didn't notice this issue when it was created!
