### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by whitverj** [JeremyAgost/Hancock#4]
There appears to be some work necessary after opening the Xcode project in order to get the project to actually build.  I'm not finding any documentation on that, however, and I'm not a developer by trade.  Feeling a bit lost.  Would love to make use of the tool, but I can't get a binary to build for the life of me.

**Comment by jazzace** [comment]
The latest release of most GitHub projects can be found by adding `/releases` to the end of the project URL (e.g., https://github.com/JeremyAgost/Hancock/releases). Version 1.2 is available there.

**Comment by JeremyAgost** [comment]
I updated the project to modern automatic signing. Now, recent versions of Xcode should allow you to just hit "Build" after you select a team in the Signing pane of the project settings. I also released [version 1.2.1](https://github.com/JeremyAgost/Hancock/releases/tag/v1.2.1), which is notarized for Catalina.
